service: usermanagement

provider:
  name: aws
  runtime: python3.8

functions:
  postUserDetails:
    handler: handler.postUserDetails
  getUserDetails:
    handler: handlerAuth.getUserDetails
  getUserQuestion:
    handler: handlerQuestion.getUserQuestion

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
